<?php

/**
 * Custom helper function to get the real client IP.
 */
function _ip_anonymisation_helper_get_client_ip() {
  // Prioritise IP from proxy.
  if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $ip_address = $_SERVER['HTTP_CLIENT_IP'];
  }
  // Next prioritise IP from proxy in another format.
  elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $ip_address = $_SERVER['HTTP_X_FORWARDED_FOR'];
  }
  // If all else fails, use the remote client IP.
  else {
    // @codingStandardsIgnoreLine
    $ip_address = $_SERVER['REMOTE_ADDR'];
  }
  return $ip_address;
}
